### ISSUE TITLE
Integrate image per post

### ISSUE THREAD

**Issue by ohrie** [CargoRocket/website#2]
We want individual header-image per post. This should be displayed also in blog overview.
The image should be declared in the YAML on top of the file.

**Comment by TheNewCivilian** [comment]
Honestly I believe we don't need that right now. I like the simplistic design and I believe that thumbnails or similar images would be either to technical to look good or just random stock images which dont say anything.

**Comment by ohrie** [comment]
We can close this is you want

**Comment by TheNewCivilian** [comment]
Sure or we check if we can create a good looking design. If it fits nicely done we might still be able to add such images.

**Comment by ohrie** [comment]
For me it's ok to close it and open it again if we need it :)
Therefore I would close it
